In [1]:
# Importando a biblioteca
import numpy as np 

In [2]:
quantidade_produtos = [10, 5, 3, 8] #Lista
custo_produtos = [5, 10, 2, 3] #Lista
array_quantidade = np.array(quantidade_produtos) #Array
array_custo = np.array(custo_produtos)

faturamento = array_quantidade * array_custo
print (faturamento)
print (type(faturamento))


[50 50  6 24]
<class 'numpy.ndarray'>


In [3]:
# Gerar um array automático
np.arange(10,21) #Sem passo

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
# Gerar um array com passo
np.arange (10,20,2) #Sobe de dois em dois


array([10, 12, 14, 16, 18])

Criar duas listas:
- 5 produtos (apenas inserir valores)
- A primeira lista, o custo da venda.
- A segunda lista, o preço de venda.
Desafio: Calcular o lucro de cada produto.

In [5]:
preco_custo = [13, 8, 15, 12, 5]
custo_venda = [25, 14, 15, 16, 5]
array_quantidade = np.array(preco_custo)
array_custo_venda = np.array(custo_venda)

custo = array_quantidade - array_custo_venda
print (custo)

[-12  -6   0  -4   0]


In [6]:
salarios = np.array ([2,3,4,5,6,500])
maior_salario = np.max(salarios)
print(maior_salario)

500


In [7]:
menor_salario = np.min(salarios)
print(menor_salario)

2


In [8]:
media_salarios = np.mean(salarios)
print(f"{media_salarios:.2f}")

86.67


In [9]:
mediana_salarios = np.median(salarios)
print(mediana_salarios)

4.5


In [10]:
desvio_padrao = np.std(salarios)
print (desvio_padrao)


184.852794286577


Criar uma lista de vendas por dia
vendas = [10,20,45,5,90]
Exibir a maior venda
Exibir a menor venda
Exibir a média de vendas
Exibir a mediana de vendas

In [12]:
venda = np.array([10,20,45,5,90])
maior_venda = np.max(venda)
print (maior_venda)


90


In [13]:
menor_venda = np.min(venda)
print (menor_venda)

5


In [15]:
vendas_media = np.mean (venda)
print (vendas_media)

34.0
